<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scxml</string>
	</array>
	<key>name</key>
	<string>THOT SCXML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\X?\&lt;style(\s*+\w+=?"?)+\&gt;\X*?\{\`$</string>
			<key>comment</key>
			<string>style block</string>
			<key>end</key>
			<string>\X?\`\}\X*?\&lt;\/style\&gt;</string>
			<key>name</key>
			<string>source.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.babeljs</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.scxml</string>
	<key>uuid</key>
	<string>8b9e41c8-3054-4848-a78a-61d23eab9034</string>
</dict>
</plist>
